### ISSUE TITLE
After syncing from gpodder to kde kasts all episodes are marked played

### ISSUE THREAD

**Issue by moritztw** [thrillfall/nextcloud-gpodder#106] opened 2022-11-14 16:10 UTC
I'm sorry if I'm wrong with the terminology, as English is not my first language.

I use nextcloud-gpodder for syncing my podcasts between Antennapod and KDE Kasts (which I run on my Ubuntu). All of the syncing works fine and out of the box. Exept only the "currently" playing episode gets synced into the Quenue. The other episodes does not appear there. 

I'm not sure if this is either a bug and therefore an issue here or if I'm doing a feature request right now.

Thanks a lot for this great piece of software btw!

## EDIT: 
Taking a further look inside KDE Kasts I can see, that all episodes except the currently playing one are marked played. Luckily I've seen it bevore it got synced back to AntennaPod.

### System:
Nextcloud Hub 3 (25.0.0) 

KDE Kasts 22.09 on Ubuntu 20.04.3 LTS installed via flathub

AntennaPod installed from Google AppStore on Pixel 6a (Android 13) 

## EDIT 2:
A quick look into Nextcloud shows, that the showed playing time of the podcasts matches the actual listening time. I'm not entirely sure, if the problem occurs at the syncinc instance or if KDE Kasts messes things up.

**Comment by JonOfUs** [comment] 2022-11-14 17:02
Hi there,
the sync between AntennaPod and Kasts can only synchronize the episode timestamps (your listen position in an episode) and subscriptions, so which episodes are in your queue cannot be synced sadly. There is a plan to enable queue synchronization, but it's yet in the far future.
So not a bug, but you don't need to open a feature request. There is a thread in the GitHub Discussions already which you can join or take a look at https://github.com/OpenPodcastAPI .

To the problem that all episodes in Kasts are marked as played:
When adding a new podcast, Kasts marks all old episodes as played by default. This marking, however, won't get synchronized. Whether an episode was played will be synchronized when you explicitly listen to the episode.
You can disable the feature that all episodes in newly-added podcasts get marked as played in the Kasts settings, I think somewhere in the General tab.

**Comment by thrillfall** [comment] 2023-01-24 18:32
Is there any news to this? Otherwise I'd close this being stale

**Closed** 2023-01-31 11:52 UTC

**Comment by timkrief** [comment] 2025-09-08 09:40
Hi, I encountered this issue and I thought this would be a solution:

> You can disable the feature that all episodes in newly-added podcasts get marked as played in the Kasts settings, I think somewhere in the General tab.

But here are the options:

<img width="557" height="220" alt="Image" src="https://github.com/user-attachments/assets/6f3b8ded-615d-4b4b-a538-c64ed6ecc5b5" />

There are no option to use the state from the server.
