### ISSUE TITLE
Errors when trying to log in from AntennaPod

### ISSUE THREAD

**Issue by xyzroller** [thrillfall/nextcloud-gpodder#55] opened 2022-03-14 07:15 UTC
I am trying to sync AntennaPod with the GPodderSync nextcloud app but have various errors.

Nextcloud version: 23.0.2
GPodder Sync version: 3.2.0
AntennaPod version: 2.5.0 from F-Droid
Nextcloud Android app version: 3.19.0 from F-Droid

My nextcloud instance is located at `https://mydomain.tld/nextcloud/` and is set up with 2FA. My Android nextcloud app is logged in and works fine.

I go to `AntennaPod Settings -> Synchroniszation -> Choose synchronization provider` and I select the Nextcloud option.

I am asked to enter the hostname.

- If I enter `mydomain.tld`, I get "Return code 404"
- If I enter `https://mydomain.tld`, I get "Return code 404"
- If I enter `mydomain.tld/nextcloud`, I get "Return code 404"
- If I enter `https://mydomain.tld/nextcloud`, I get "Return code 404"
- If I enter `mydomain.tld/nextcloud/` (note trailing slash), I get "Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject"
- If I enter `https://mydomain.tld/nextcloud/` (note trailing slash), I get "Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject"

How can I log in from AntennaPod?

Thanks in advance!

**Comment by xyzroller** [comment] 2022-03-14 07:22
Update: I also tried via `AntennaPod Settings -> Synchroniszation -> Choose synchronization provider`, but choosing the GPodder.net option with my Nextcloud instance as a custom server and using a nextcloud app password (to get around 2FA). The same errors occurred.

**Comment by JonOfUs** [comment] 2022-03-14 08:23
Hi,

the problem is that the synchronization not yet works with Nextcloud in a subfolder. It's a problem already described [in the Antennapod forum](https://forum.antennapod.org/t/nextcloud-gpodder-login-question/1747), so it will probably be fixed soon.

It has to be fixed within Antennapod, so there's nothing we can do here. You could create an issue for it in the [Antennapod repository](https://github.com/AntennaPod/AntennaPod). If I find the time, I'm going to take a look at the problem inside Antennapod.

I will close this issue since there's nothing to do in this repo.

**Closed** 2022-03-14 08:27 UTC

**Comment by xyzroller** [comment] 2022-03-14 09:09
OK, understood. Thanks for the quick feedback.

**Comment by xyzroller** [comment] 2022-03-14 09:18
Just for info - looks like it's already fixed and scheduled for an upcoming AntennaPod release:
https://github.com/AntennaPod/AntennaPod/pull/5751

**Comment by JonOfUs** [comment] 2022-03-14 11:07
Great! I didn't know about this, thanks for sharing.
