### ISSUE TITLE
Sync does not sync "done episodes"

### ISSUE THREAD

**Issue by Linkinsoldier** [thrillfall/nextcloud-gpodder#92] opened 2022-09-11 19:48 UTC
I use this app with antennapod (current version from f-droid). It synced my Podcasts and the current playing status of the episodes i was currently not finished listening. However it does NOT sync whether an episode is already listened (completed).

Is this a known bug? this would be very helpful for me!

**Comment by JonOfUs** [comment] 2022-09-12 20:27
You mean that it does not mark episodes as played on the other sync side?

I think I once heard about that played states of episodes that were played before sync was initially set up don't get synced. You could test that by playing an episode to the end (e.g. skipping a lot) and then checking whether the episode gets marked as played on the other device. If this is the case, the problem is that AntennaPod does not send the old states. We can't do anything over here then, you would probably have to open a feature request in the AntennaPod repo or search/ask in the AntennaPod forum ([forum.antennapod.com](https://forum.antennapod.com)) whether there is a workaround for this.

**Comment by JonOfUs** [comment] 2022-09-12 20:31
You mean that it does not mark episodes as played on the other sync side?

I think I once heard about that played states of episodes that were played before sync was initially set up don't get synced. You could test that by playing an episode to the end (e.g. skipping a lot) and then checking whether the episode gets marked as played on the other device. If this is the case, the problem is that AntennaPod does not send the old states. We can't do anything over here then, you would probably have to open a feature request in the AntennaPod repo or search/ask in the AntennaPod forum ([forum.antennapod.com](https://forum.antennapod.com)) whether there is a workaround for this.

Edit: I read something about that the 'force full sync' function could help syncing more episode states. Did you try this?

**Comment by Linkinsoldier** [comment] 2022-09-13 17:15
> You mean that it does not mark episodes as played on the other sync side?
> 
> I think I once heard about that played states of episodes that were played before sync was initially set up don't get synced. You could test that by playing an episode to the end (e.g. skipping a lot) and then checking whether the episode gets marked as played on the other device. If this is the case, the problem is that AntennaPod does not send the old states. We can't do anything over here then, you would probably have to open a feature request in the AntennaPod repo or search/ask in the AntennaPod forum ([forum.antennapod.com](https://forum.antennapod.com)) whether there is a workaround for this.
> 
> Edit: I read something about that the 'force full sync' function could help syncing more episode states. Did you try this?

Thank you for your response. Dont ask, me why, but redoing the manual sinc on both devices fixed the issue. I have been using only one device for months now and i tried everything on the new device (also force full sync). However a full forced sync on the first device seemed to be necessary (don't know why ... since it was only one device).

either way: seems to work now. Thank you very much! I will keep an eye on this!

**Closed** 2022-09-13 17:15 UTC

**Comment by Mannshoch** [comment] 2025-02-14 21:52
I have the same problem here with antennapod.
My problem is, the other Device does not anymore exist. 
is it possible to somehow set all more than 90% played as finished directly on nextcloud?

**Comment by JonOfUs** [comment] 2025-02-16 11:26
With some SQL magic, it might be possible to change these timestamps. But I don't exactly know whether that would work.
You could set all `position` fields to the same value of the `total` field, if the `position` field is at least 0.9*`total` in the `gpodder_episode_action` table. But again, I don't know for sure that it would work, and I'm not deep enough in SQL to write you a query like that.
