### ISSUE TITLE
[Feature Request] Sync with news app

### ISSUE THREAD

**Issue by LeifAndersen** [thrillfall/nextcloud-gpodder#67] opened 2022-05-07 21:08 UTC
I find the nextcloud news app (https://github.com/nextcloud/news) to be a good way to manage RSS feeds. Unfortunately its not ideal for a podcast client (I'd rather use something like AntennaPod).

Unfortunately it seems like nextcloud-gpodder an antennapod keep seperate databases for RSS feeds. It'd be nice if gpodder could use a podcast folder in news, or news could have a folder for gpoddersync if installed.

I'm also going to open a duplicate of this feature request in the news app.

**Comment by citizenserious** [comment] 2022-05-08 12:34
**[Feature Request] Sync with Music app**
The music app has a podcast section too, which uses RSS feeds.
So it would be nice if it was synced (:

I'm going to open a duplicate of this feature request in the music app too.

**Comment by thrillfall** [comment] 2022-05-08 17:31
I'd be really interested in any proposal that does this without hard coupling

**Closed** 2022-05-09 17:10 UTC
