### ISSUE TITLE
Error with Antennapod-Sync 

### ISSUE THREAD

**Issue by versus167** [thrillfall/nextcloud-gpodder#109] opened 2023-02-15 12:25 UTC
For a few hours now, an error occurs during synchronization in Antennapod. A look at the log files in nextcloud brings this:

[index] Fehler: Exception: Call to a member function getId() on null in file '/var/snap/nextcloud/33587/nextcloud/extra-apps/gpoddersync/lib/Core/EpisodeAction/EpisodeActionSaver.php' line 81 at <<closure>>

0. /snap/nextcloud/33587/htdocs/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /snap/nextcloud/33587/htdocs/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /snap/nextcloud/33587/htdocs/lib/base.php line 1047
   OC\Route\Router->match()
3. /snap/nextcloud/33587/htdocs/index.php line 36
   OC::handleRequest()

POST //index.php/apps/gpoddersync/episode_action/create
from 80.187.117.42 by vsuess at 2023-02-15T10:34:35+00:00

What can be the problem?

**Comment by JonOfUs** [comment] 2023-02-15 15:13
Hmm... This issue sometimes happened in the past if episodes had a media URL that was longer than 500 characters (https://github.com/thrillfall/nextcloud-gpodder/issues/81). But it should have been fixed in v3.7.0.
What version of Nextcloud-gpodder are you using?

**Comment by versus167** [comment] 2023-02-15 15:59
It is GPodderSync 3.7.1 and Nextcloud 25.0.3 ( exactly 25.0.3snap2    rev. 33587)

**Comment by JonOfUs** [comment] 2023-02-15 16:59
It's possible that the problem comes from an episode that was uploaded prior to 3.7.0 and had a very long media url (therefore only 500 chars of the media url were stored) and that AntennaPod now tries to update.
Nextcloud-Gpodder compares the first 500 characters to look whether an episode is already in the database (for compability with old MariaDB instances only the first 500). Here, your episode was found (since the first 500 chars are identical). But when Nextcloud-gpodder then tried to update the corresponding episode, it used the full media URL and not only the first 500 characters and the couldn't find the episode anymore (since only the first 500 characters match).

Can you take a look at the episodes that you last listened to before the errors started and check whether their media URL is very long? (>500 chars) You can get the media URL in AntennaPod, go to the episode, click on the dot menu top right, click on 'share', select 'media address'.
This would help to make sure this is truly the problem here.

**Comment by versus167** [comment] 2023-02-15 17:24
The last complete and the actual episod are both wide under 500 characters. 

the last: https://logbuch-netzpolitik.de/podlove/file/8463/s/feed/c/m4a/lnp446-die-laermsucht-des-poebels.m4a
the current: https://audio.podigee-cdn.net/949152-m-86a417529b1de3ad1a52d40adfcdf7c9.mp3?source=feed

The error first attempt about 2 AM. But antennapod has no new episode downloaded this night and I sleep at this time ;)

**Comment by JonOfUs** [comment] 2023-02-15 18:13
Hmm... That's very weird. Then I don't know at all what leads to the errors.

It's always good to test whether a complete sync (Antennapod > settings > sync > force full sync) or logging out and then logging back in (in AntennaPod) helps.

Is there maybe an episode that was downloaded automatically last night? That could have been synchronized as well.

If this doesn't help, you can check whether there are any more infos in the logs and send them in here. If you have access to a up-to-date database dump, you can send the extract regarding `oc_gpodder_episode_actions` (be careful not to send more as it contains private data) to me so that I can further investigate this (my email: username at lastname dot eu).

**Comment by sellth** [comment] 2023-02-16 22:45
I have the same issue with AntennaPod, also since a few days. Forced full sync also fails.

**Comment by Milaoooo** [comment] 2023-02-17 11:17
yup, for me the same..

**Comment by JonOfUs** [comment] 2023-02-17 11:26
Information that could help identify the problem here:
- AntennaPod version, Database type and version, php version
- Any logs in connection with the errors (AntennaPod logs as well)
- Any changes you know that happened directly before the errors occured (e.g. updates, ...)

**Comment by thrillfall** [comment] 2023-02-17 16:12
I have it too. It is the same behavior. Create EpisodeAction fails because there is already one. The the update fails because the EpisodeAction is not found in Database 🤷 
I'll see to it to get it debugged

**Comment by foe05** [comment] 2023-02-17 18:46
Hei there. 

I encounter the same error after upgrading to nextcloud 25.0.3. before that (NC 24.x) the service ran like a charme.

Tried already to reconnect/reauthenticate/force sync... No success so far.

Antenna pod version 2.7.1
Gpoddersync 3.7.1
Nextcloud see above 

Thanks so far.

**Comment by art1sec** [comment] 2023-02-19 12:10
I have the same issue here. Syncing with AntennaPod works for a few podcasts, then it stops with HTTP 500:
`POST /next/index.php/apps/gpoddersync/episode_action/create HTTP/1.0" 500 3874 "-" "AntennaPod/2.7.1"`

Syncing with Kasts still worked. Downgrading AntennaPod from 2.7.1 to 2.6.2 solved the issue for me. So it looks like the problem is AntennaPod, not Nextcloud.

**Comment by strobeltobias** [comment] 2023-02-20 07:58
I noticed the same error occurring since a few days. Some more detailed logs:
```json
{
  "reqId": "wKrUP7BTgabFyT0epFDO",
  "level": 3,
  "time": "2023-02-20T07:49:39+00:00",
  "remoteAddr": "2a00:20:301b:2f40:7b7b:b44c:844e:a58a",
  "user": "tobias",
  "app": "index",
  "method": "POST",
  "url": "//index.php/apps/gpoddersync/episode_action/create",
  "message": "Call to a member function getId() on null in file '/var/www/html/custom_apps/gpoddersync/lib/Core/EpisodeAction/EpisodeActionSaver.php' line 81",
  "userAgent": "AntennaPod/2.7.1",
  "version": "25.0.3.2",
  "exception": {
    "Exception": "Exception",
    "Message": "Call to a member function getId() on null in file '/var/www/html/custom_apps/gpoddersync/lib/Core/EpisodeAction/EpisodeActionSaver.php' line 81",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 172,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\GPodderSync\\Controller\\EpisodeActionController"
          },
          "create"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 298,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\GPodderSync\\Controller\\EpisodeActionController",
          "create",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          [
            "gpoddersync.episode_action.create"
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/base.php",
        "line": 1047,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/apps/gpoddersync/episode_action/create"
        ]
      },
      {
        "file": "/var/www/html/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 165,
    "Previous": {
      "Exception": "Error",
      "Message": "Call to a member function getId() on null",
      "Code": 0,
      "Trace": [
        {
          "file": "/var/www/html/custom_apps/gpoddersync/lib/Core/EpisodeAction/EpisodeActionSaver.php",
          "line": 53,
          "function": "updateEpisodeAction",
          "class": "OCA\\GPodderSync\\Core\\EpisodeAction\\EpisodeActionSaver",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/html/custom_apps/gpoddersync/lib/Controller/EpisodeActionController.php",
          "line": 44,
          "function": "saveEpisodeActions",
          "class": "OCA\\GPodderSync\\Core\\EpisodeAction\\EpisodeActionSaver",
          "type": "->",
          "args": [
            [
              [
                "https://www.hoerspielundfeature.de/hoerspiel-122.xml",
                "https://podcast-mp3.dradio.de/podcast/2022/10/27/urbanes_narrativ_drk_20221027_2250_f5038442.mp3",
                "https://podcast-mp3.dradio.de/podcast/2022/10/27/urbanes_narrativ_drk_20221027_2250_f5038442.mp3?refId=hoerspiel-122",
                "play",
                "2023-02-16T01:42:51",
                "And 3 more entries, set log level to debug to see all entries"
              ],
              [
                "https://feeds.metaebene.me/lnp/m4a",
                "https://logbuch-netzpolitik.de/podlove/file/8494/s/feed/c/m4a/lnp452-mit-rechten-dingen.m4a",
                "podlove-2023-02-01t02:33:47+00:00-0388d95cf96eed7",
                "play",
                "2023-02-16T07:10:44",
                "And 3 more entries, set log level to debug to see all entries"
              ],
              [
                "https://feeds.metaebene.me/lnp/m4a",
                "https://logbuch-netzpolitik.de/podlove/file/8494/s/feed/c/m4a/lnp452-mit-rechten-dingen.m4a",
                "podlove-2023-02-01t02:33:47+00:00-0388d95cf96eed7",
                "play",
                "2023-02-16T07:18:24",
                "And 3 more entries, set log level to debug to see all entries"
              ],
              [
                "https://feeds.metaebene.me/lnp/m4a",
                "https://logbuch-netzpolitik.de/podlove/file/8494/s/feed/c/m4a/lnp452-mit-rechten-dingen.m4a",
                "podlove-2023-02-01t02:33:47+00:00-0388d95cf96eed7",
                "play",
                "2023-02-16T07:19:19",
                "And 3 more entries, set log level to debug to see all entries"
              ],
              [
                "https://feeds.br.de/iq-wissenschaft-und-forschung/feed.xml",
                "https://media.neuland.br.de/file/1910218/c/feed/anfaellig-fuer-viren-im-winter-kaelte-schwaecht-die-abwehr-in-der-nase-1.mp3",
                "0b208c11-3883-4d6e-95e3-cb72bc7e70f4",
                "play",
                "2023-02-16T13:48:45",
                "And 3 more entries, set log level to debug to see all entries"
              ],
              "And 25 more entries, set log level to debug to see all entries"
            ],
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 225,
          "function": "create",
          "class": "OCA\\GPodderSync\\Controller\\EpisodeActionController",
          "type": "->",
          "args": []
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 133,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OCA\\GPodderSync\\Controller\\EpisodeActionController"
            },
            "create"
          ]
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/App.php",
          "line": 172,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OCA\\GPodderSync\\Controller\\EpisodeActionController"
            },
            "create"
          ]
        },
        {
          "file": "/var/www/html/lib/private/Route/Router.php",
          "line": 298,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::",
          "args": [
            "OCA\\GPodderSync\\Controller\\EpisodeActionController",
            "create",
            {
              "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
            },
            [
              "gpoddersync.episode_action.create"
            ]
          ]
        },
        {
          "file": "/var/www/html/lib/base.php",
          "line": 1047,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->",
          "args": [
            "/apps/gpoddersync/episode_action/create"
          ]
        },
        {
          "file": "/var/www/html/index.php",
          "line": 36,
          "function": "handleRequest",
          "class": "OC",
          "type": "::",
          "args": []
        }
      ],
      "File": "/var/www/html/custom_apps/gpoddersync/lib/Core/EpisodeAction/EpisodeActionSaver.php",
      "Line": 81
    },
    "CustomMessage": "--"
  },
  "id": "63f3262e174cc"
}
```

**Comment by thrillfall** [comment] 2023-02-21 22:24
For me the issue is that i have 2 "colliding" episode_actions in the database:
for the first episode = "https://bla.com" and guid = "https://bla.com?ref=story"
and the second has the values the other way around. Thus we get an `MultipleObjectsReturnedException` in `\OCA\GPodderSync\Db\EpisodeAction\EpisodeActionMapper::findByEpisodeIdentifier:L64` 

too late today to find a fix for this. i guess this requires us to get rid of one episode_action. but which one?

**Comment by JonOfUs** [comment] 2023-02-22 11:52
Ahh, that makes sense.

If this is also the source of the other problems, then maybe the problem could be that AntennaPod sometimes drops the GET parameters behind the `?` and sometimes doesn't (or the rss feed does this on its own).

The example from @strobeltobias looks like this happens:
```json
[
  "https://www.hoerspielundfeature.de/hoerspiel-122.xml",
  "https://podcast-mp3.dradio.de/podcast/2022/10/27/urbanes_narrativ_drk_20221027_2250_f5038442.mp3",
  "https://podcast-mp3.dradio.de/podcast/2022/10/27/urbanes_narrativ_drk_20221027_2250_f5038442.mp3?refId=hoerspiel-122",
  "play",
  "2023-02-16T01:42:51",
  "And 3 more entries, set log level to debug to see all entries"
],
```
`episode url` doesn't have the parameter attached, while `guid` has. And in the rss feed, both of them have the parameter.


A hotfix could be that these cases are simply ignored (l80, if null return null).
And a fix could be to have distinct episode finders in `EpisodeActionMapper`, specifically for `episode` or `guid`. This way, this shouldn't happen anymore and the mapping should still be correct.

**Comment by thrillfall** [comment] 2023-02-22 18:11
Yes, I also think the "magic" episode action finding by guid and/or episode can't deal with those situations. Splitting it sounds like a good and overdue approach.

The race for a test and fix is open 🚲

**Comment by thrillfall** [comment] 2023-02-24 18:02
still fails for me.

**Comment by sellth** [comment] 2023-02-24 18:04
Same for me.

```
[index] Error: OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://podcast-mp3.dradio.de/podcast/2022/08/18/der_politikp...' for key 'gpodder_episode_user_id' at <<closure>>
```

**Comment by thrillfall** [comment] 2023-02-24 19:56
having two "identifiers" really messes with system logic. Fix is ready

**Comment by thrillfall** [comment] 2023-02-24 20:15
probable fix #117

**Comment by Linkinsoldier** [comment] 2023-02-24 20:56
I was about to create a bug ticket for this, but found this thread instead. Just made an Update to gpoddersync 3.7.3. And this Fixed it for me.

Thank you!

**Comment by thrillfall** [comment] 2023-02-24 22:09
Some podcast provider tend to modify the episode  URLs by adding parameters or removing them. Since we use those URLs to identify podcast episodes as a fallback when there is/was no guid provided this is bound to conflict.

**Closed by thrillfall** 2023-02-24 22:09 UTC

**Comment by foe05** [comment] 2023-02-26 20:49
Great. Works perfectly for me. Thanks a lot.
